# Generated by Django 3.2.8 on 2021-10-26 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211026_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='note',
            new_name='product',
        ),
    ]
